#server:
#  port: 8081
#  servlet:#    context-path: /boot
spring:  datasource:    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.32.144:3306/springboot?characterEncoding=UTF-8
    username: root
    password: 123456
  profiles:    active: test#  使用jsp的时候需要加上
#  mvc:#    view:#      prefix: /jsp/
#      suffix: .jsp

#使用thymeleaf模板时候加上  thymeleaf:
    mode: HTML5
    encoding: utf-8    cache: false
mybatis:  mapper-locations: com/aubrey/mapper/impl/*.xml

logging:  level:    root: debug
    





  
  