spring:
  datasource:   ##配置数据源类型和连接信息
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.32.130:3306/springboot?characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update
    show-sql: true