server:
  port: 8888

spring:
  application:
    name: config-server
  #    托管本地配置，文件件命名格式为 客户端的spring.application.name 加上profile后缀
  #  URL与配置文件的映射关系如下：
  #
  #  /{application}/{profile}[/{label}]
  #  /{application}-{profile}.yml
  #  /{label}/{application}-{profile}.yml
  #  /{application}-{profile}.properties
  #  /{label}/{application}-{profile}.properties
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
  profiles:
    active: native # 配置使用本地储存

eureka:
  instance:
    #        表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
    lease-expiration-duration-in-seconds: 90
    #    心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
#      ,http://localhost:8758/eureka/
    #   表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    registry-fetch-interval-seconds: 30
    healthcheck:
      enabled: true                           # 开启健康检查（依赖spring-boot-starter-actuator）


#git 远程配置
#spring.cloud.config.server.git.uri: https://github.com/forezp/SpringcloudConfig/
#spring.cloud.config.server.git.searchPaths: respo
#spring.cloud.config.label: master
#spring.cloud.config.server.git.username:
#spring.cloud.config.server.git.password:


